services:
  - type: web
    name: smartservice-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic
    startCommand: |
      python manage.py migrate &&
      python manage.py create_admin &&
      gunicorn smartservice.wsgi:application
