# Generated by Django 5.2.4 on 2025-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_providerservice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
