# Generated by Django 5.2.4 on 2025-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_full_name_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('provider', 'Service Provider'), ('admin', 'Admin')], max_length=10),
        ),
    ]
